CREATE TABLE persons
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_persons PRIMARY KEY (id)
);

ALTER TABLE persons
    ADD CONSTRAINT UniqueLogin UNIQUE (login);

insert into persons (login, password) values ('parsentev', '123');
insert into persons (login, password) values ('ban', '123');
insert into persons (login, password) values ('ivan', '123');

CREATE TABLE employees
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    surname  VARCHAR(255),
    itin      BIGINT                                 NOT NULL,
    hired_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

ALTER TABLE employees
    ADD CONSTRAINT UniqueItin UNIQUE (itin);

CREATE TABLE employees_persons
(
    employee_id BIGINT NOT NULL,
    person_id   BIGINT NOT NULL,
    CONSTRAINT pk_employees_persons PRIMARY KEY (employee_id, person_id)
);

ALTER TABLE employees_persons
    ADD CONSTRAINT uc_employees_persons_person UNIQUE (person_id);

ALTER TABLE employees_persons
    ADD CONSTRAINT fk_empper_on_employee FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE employees_persons
    ADD CONSTRAINT fk_empper_on_person FOREIGN KEY (person_id) REFERENCES persons (id);

INSERT INTO employees (name, surname, itin, hired_at)
VALUES ('Petr', 'Arsentev', 123456789, NOW());

INSERT INTO employees (name, surname, itin, hired_at)
VALUES ('John', 'Doe', 987654321, NOW());

INSERT INTO employees (name, surname, itin, hired_at)
VALUES ('Joanna', 'Doe', 543789214, NOW());

insert into employees_persons (employee_id, person_id) values (1, 1);
insert into employees_persons (employee_id, person_id) values (2, 2);
insert into employees_persons (employee_id, person_id) values (3, 3);
