CREATE TABLE persons
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_persons PRIMARY KEY (id)
);

ALTER TABLE persons
    ADD CONSTRAINT UniqueLogin UNIQUE (login);

insert into persons (login, password) values ('parsentev', '123');
insert into persons (login, password) values ('ban', '123');
insert into persons (login, password) values ('ivan', '123');